version: "3.5"

services:
  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  api:
    depends_on:
      - "postgres"
    container_name: xor-api
    image: github.com/dyrector-io/xor/api:v1
    build:
      context: api
    ports:
      - "3333:3333"
    environment:
      DSN: ${DSN:-host=172.17.0.1 user=postgres password=password dbname=postgres port=5432 sslmode=disable}
  ui:
    depends_on:
      - "api"
    container_name: xor-ui
    image: github.com/dyrector-io/xor/ui:v1
    volumes:
      - "./web/nginx/ui.conf:/etc/nginx/conf.d/ui.conf"
    build:
      context: web
    ports:
      - "8080:8080"
    environment:
      PUBLIC_API_URL: ""

volumes:
  postgres:
