version: "3.5"

services:
  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  api:
    container_name: xor-api
    image: github.com/dyrector-io/xor/api:v1
    build:
      context: api
    ports:
      - "3333:3333"
    environment:
      DSN: ${DSN:-host=localhost user=postgres password=password dbname=postgres port=5432 sslmode=disable}

volumes:
  postgres:
